using System;
using System.Collections.Generic;
using System.Text;

namespace CrossChess.Helpers
{
    public class IconHelper
    {
        public static readonly string FontAwesomeResource = "FontAwesomeIconFont";
        public static readonly string MaterialResource = "MaterialIconFont";
        //public static readonly string FontAwesomeResource = "/Assets/Fonts/FontAwesome.otf#Font Awesome 5 Free";
        //public static readonly string MaterialResource = "/Assets/Fonts/MaterialIcons-Regular.ttf#Material Icons";

        public static Dictionary<FontAwesomeIconType, string> FontAwesomeValues => GetFontIcons();
        static Dictionary<FontAwesomeIconType, string> _fontData;

        private static Dictionary<FontAwesomeIconType, string> GetFontIcons()
        {
            if (_fontData == null)
            {
                _fontData = new FontIconContainer().FontAwesomeValues;
            }
            return _fontData;
        }

    }

    class FontIconContainer
    {
        internal readonly Dictionary<FontAwesomeIconType, string> FontAwesomeValues = new Dictionary<FontAwesomeIconType, string>()
        {
                { FontAwesomeIconType.GlassMartini , "\uf000"},
                { FontAwesomeIconType.Music , "\uf001"},
                { FontAwesomeIconType.Search , "\uf002"},
                { FontAwesomeIconType.Heart , "\uf004"},
                { FontAwesomeIconType.Star , "\uf005"},
                { FontAwesomeIconType.User , "\uf007"},
                { FontAwesomeIconType.Film , "\uf008"},
                { FontAwesomeIconType.ThLarge , "\uf009"},
                { FontAwesomeIconType.Th , "\uf00a"},
                { FontAwesomeIconType.ThList , "\uf00b"},
                { FontAwesomeIconType.Check , "\uf00c"},
                { FontAwesomeIconType.Times , "\uf00d"},
                { FontAwesomeIconType.SearchPlus , "\uf00e"},
                { FontAwesomeIconType.SearchMinus , "\uf010"},
                { FontAwesomeIconType.PowerOff , "\uf011"},
                { FontAwesomeIconType.Signal , "\uf012"},
                { FontAwesomeIconType.Cog , "\uf013"},
                { FontAwesomeIconType.Home , "\uf015"},
                { FontAwesomeIconType.Clock , "\uf017"},
                { FontAwesomeIconType.Road , "\uf018"},
                { FontAwesomeIconType.Download , "\uf019"},
                { FontAwesomeIconType.Inbox , "\uf01c"},
                { FontAwesomeIconType.Redo , "\uf01e"},
                { FontAwesomeIconType.Sync , "\uf021"},
                { FontAwesomeIconType.ListAlt , "\uf022"},
                { FontAwesomeIconType.Lock , "\uf023"},
                { FontAwesomeIconType.Flag , "\uf024"},
                { FontAwesomeIconType.Headphones , "\uf025"},
                { FontAwesomeIconType.VolumeOff , "\uf026"},
                { FontAwesomeIconType.VolumeDown , "\uf027"},
                { FontAwesomeIconType.VolumeUp , "\uf028"},
                { FontAwesomeIconType.Qrcode , "\uf029"},
                { FontAwesomeIconType.Barcode , "\uf02a"},
                { FontAwesomeIconType.Tag , "\uf02b"},
                { FontAwesomeIconType.Tags , "\uf02c"},
                { FontAwesomeIconType.Book , "\uf02d"},
                { FontAwesomeIconType.Bookmark , "\uf02e"},
                { FontAwesomeIconType.Print , "\uf02f"},
                { FontAwesomeIconType.Camera , "\uf030"},
                { FontAwesomeIconType.Font , "\uf031"},
                { FontAwesomeIconType.Bold , "\uf032"},
                { FontAwesomeIconType.Italic , "\uf033"},
                { FontAwesomeIconType.TextHeight , "\uf034"},
                { FontAwesomeIconType.TextWidth , "\uf035"},
                { FontAwesomeIconType.AlignLeft , "\uf036"},
                { FontAwesomeIconType.AlignCenter , "\uf037"},
                { FontAwesomeIconType.AlignRight , "\uf038"},
                { FontAwesomeIconType.AlignJustify , "\uf039"},
                { FontAwesomeIconType.List , "\uf03a"},
                { FontAwesomeIconType.Outdent , "\uf03b"},
                { FontAwesomeIconType.Indent , "\uf03c"},
                { FontAwesomeIconType.Video , "\uf03d"},
                { FontAwesomeIconType.Image , "\uf03e"},
                { FontAwesomeIconType.MapMarker , "\uf041"},
                { FontAwesomeIconType.Adjust , "\uf042"},
                { FontAwesomeIconType.Tint , "\uf043"},
                { FontAwesomeIconType.Edit , "\uf044"},
                { FontAwesomeIconType.StepBackward , "\uf048"},
                { FontAwesomeIconType.FastBackward , "\uf049"},
                { FontAwesomeIconType.Backward , "\uf04a"},
                { FontAwesomeIconType.Play , "\uf04b"},
                { FontAwesomeIconType.Pause , "\uf04c"},
                { FontAwesomeIconType.Stop , "\uf04d"},
                { FontAwesomeIconType.Forward , "\uf04e"},
                { FontAwesomeIconType.FastForward , "\uf050"},
                { FontAwesomeIconType.StepForward , "\uf051"},
                { FontAwesomeIconType.Eject , "\uf052"},
                { FontAwesomeIconType.ChevronLeft , "\uf053"},
                { FontAwesomeIconType.ChevronRight , "\uf054"},
                { FontAwesomeIconType.PlusCircle , "\uf055"},
                { FontAwesomeIconType.MinusCircle , "\uf056"},
                { FontAwesomeIconType.TimesCircle , "\uf057"},
                { FontAwesomeIconType.CheckCircle , "\uf058"},
                { FontAwesomeIconType.QuestionCircle , "\uf059"},
                { FontAwesomeIconType.InfoCircle , "\uf05a"},
                { FontAwesomeIconType.Crosshairs , "\uf05b"},
                { FontAwesomeIconType.Ban , "\uf05e"},
                { FontAwesomeIconType.ArrowLeft , "\uf060"},
                { FontAwesomeIconType.ArrowRight , "\uf061"},
                { FontAwesomeIconType.ArrowUp , "\uf062"},
                { FontAwesomeIconType.ArrowDown , "\uf063"},
                { FontAwesomeIconType.Share , "\uf064"},
                { FontAwesomeIconType.Expand , "\uf065"},
                { FontAwesomeIconType.Compress , "\uf066"},
                { FontAwesomeIconType.Plus , "\uf067"},
                { FontAwesomeIconType.Minus , "\uf068"},
                { FontAwesomeIconType.Asterisk , "\uf069"},
                { FontAwesomeIconType.ExclamationCircle , "\uf06a"},
                { FontAwesomeIconType.Gift , "\uf06b"},
                { FontAwesomeIconType.Leaf , "\uf06c"},
                { FontAwesomeIconType.Fire , "\uf06d"},
                { FontAwesomeIconType.Eye , "\uf06e"},
                { FontAwesomeIconType.EyeSlash , "\uf070"},
                { FontAwesomeIconType.ExclamationTriangle , "\uf071"},
                { FontAwesomeIconType.Plane , "\uf072"},
                { FontAwesomeIconType.CalendarAlt , "\uf073"},
                { FontAwesomeIconType.Random , "\uf074"},
                { FontAwesomeIconType.Comment , "\uf075"},
                { FontAwesomeIconType.Magnet , "\uf076"},
                { FontAwesomeIconType.ChevronUp , "\uf077"},
                { FontAwesomeIconType.ChevronDown , "\uf078"},
                { FontAwesomeIconType.Retweet , "\uf079"},
                { FontAwesomeIconType.ShoppingCart , "\uf07a"},
                { FontAwesomeIconType.Folder , "\uf07b"},
                { FontAwesomeIconType.FolderOpen , "\uf07c"},
                { FontAwesomeIconType.ChartBar , "\uf080"},
                { FontAwesomeIconType.CameraRetro , "\uf083"},
                { FontAwesomeIconType.Key , "\uf084"},
                { FontAwesomeIconType.Cogs , "\uf085"},
                { FontAwesomeIconType.Comments , "\uf086"},
                { FontAwesomeIconType.StarHalf , "\uf089"},
                { FontAwesomeIconType.Thumbtack , "\uf08d"},
                { FontAwesomeIconType.Trophy , "\uf091"},
                { FontAwesomeIconType.Upload , "\uf093"},
                { FontAwesomeIconType.Lemon , "\uf094"},
                { FontAwesomeIconType.Phone , "\uf095"},
                { FontAwesomeIconType.PhoneSquare , "\uf098"},
                { FontAwesomeIconType.Unlock , "\uf09c"},
                { FontAwesomeIconType.CreditCard , "\uf09d"},
                { FontAwesomeIconType.Rss , "\uf09e"},
                { FontAwesomeIconType.Hdd , "\uf0a0"},
                { FontAwesomeIconType.Bullhorn , "\uf0a1"},
                { FontAwesomeIconType.Certificate , "\uf0a3"},
                { FontAwesomeIconType.HandPointRight , "\uf0a4"},
                { FontAwesomeIconType.HandPointLeft , "\uf0a5"},
                { FontAwesomeIconType.HandPointUp , "\uf0a6"},
                { FontAwesomeIconType.HandPointDown , "\uf0a7"},
                { FontAwesomeIconType.ArrowCircleLeft , "\uf0a8"},
                { FontAwesomeIconType.ArrowCircleRight , "\uf0a9"},
                { FontAwesomeIconType.ArrowCircleUp , "\uf0aa"},
                { FontAwesomeIconType.ArrowCircleDown , "\uf0ab"},
                { FontAwesomeIconType.Globe , "\uf0ac"},
                { FontAwesomeIconType.Wrench , "\uf0ad"},
                { FontAwesomeIconType.Tasks , "\uf0ae"},
                { FontAwesomeIconType.Filter , "\uf0b0"},
                { FontAwesomeIconType.Briefcase , "\uf0b1"},
                { FontAwesomeIconType.ArrowsAlt , "\uf0b2"},
                { FontAwesomeIconType.Users , "\uf0c0"},
                { FontAwesomeIconType.Link , "\uf0c1"},
                { FontAwesomeIconType.Cloud , "\uf0c2"},
                { FontAwesomeIconType.Flask , "\uf0c3"},
                { FontAwesomeIconType.Cut , "\uf0c4"},
                { FontAwesomeIconType.Copy , "\uf0c5"},
                { FontAwesomeIconType.Paperclip , "\uf0c6"},
                { FontAwesomeIconType.Save , "\uf0c7"},
                { FontAwesomeIconType.Square , "\uf0c8"},
                { FontAwesomeIconType.Bars , "\uf0c9"},
                { FontAwesomeIconType.ListUl , "\uf0ca"},
                { FontAwesomeIconType.ListOl , "\uf0cb"},
                { FontAwesomeIconType.Strikethrough , "\uf0cc"},
                { FontAwesomeIconType.Underline , "\uf0cd"},
                { FontAwesomeIconType.Table , "\uf0ce"},
                { FontAwesomeIconType.Magic , "\uf0d0"},
                { FontAwesomeIconType.Truck , "\uf0d1"},
                { FontAwesomeIconType.MoneyBill , "\uf0d6"},
                { FontAwesomeIconType.CaretDown , "\uf0d7"},
                { FontAwesomeIconType.CaretUp , "\uf0d8"},
                { FontAwesomeIconType.CaretLeft , "\uf0d9"},
                { FontAwesomeIconType.CaretRight , "\uf0da"},
                { FontAwesomeIconType.Columns , "\uf0db"},
                { FontAwesomeIconType.Sort , "\uf0dc"},
                { FontAwesomeIconType.SortDown , "\uf0dd"},
                { FontAwesomeIconType.SortUp , "\uf0de"},
                { FontAwesomeIconType.Envelope , "\uf0e0"},
                { FontAwesomeIconType.Undo , "\uf0e2"},
                { FontAwesomeIconType.Gavel , "\uf0e3"},
                { FontAwesomeIconType.Bolt , "\uf0e7"},
                { FontAwesomeIconType.Sitemap , "\uf0e8"},
                { FontAwesomeIconType.Umbrella , "\uf0e9"},
                { FontAwesomeIconType.Paste , "\uf0ea"},
                { FontAwesomeIconType.Lightbulb , "\uf0eb"},
                { FontAwesomeIconType.UserMd , "\uf0f0"},
                { FontAwesomeIconType.Stethoscope , "\uf0f1"},
                { FontAwesomeIconType.Suitcase , "\uf0f2"},
                { FontAwesomeIconType.Bell , "\uf0f3"},
                { FontAwesomeIconType.Coffee , "\uf0f4"},
                { FontAwesomeIconType.Hospital , "\uf0f8"},
                { FontAwesomeIconType.Ambulance , "\uf0f9"},
                { FontAwesomeIconType.Medkit , "\uf0fa"},
                { FontAwesomeIconType.FighterJet , "\uf0fb"},
                { FontAwesomeIconType.Beer , "\uf0fc"},
                { FontAwesomeIconType.HSquare , "\uf0fd"},
                { FontAwesomeIconType.PlusSquare , "\uf0fe"},
                { FontAwesomeIconType.AngleDoubleLeft , "\uf100"},
                { FontAwesomeIconType.AngleDoubleRight , "\uf101"},
                { FontAwesomeIconType.AngleDoubleUp , "\uf102"},
                { FontAwesomeIconType.AngleDoubleDown , "\uf103"},
                { FontAwesomeIconType.AngleLeft , "\uf104"},
                { FontAwesomeIconType.AngleRight , "\uf105"},
                { FontAwesomeIconType.AngleUp , "\uf106"},
                { FontAwesomeIconType.AngleDown , "\uf107"},
                { FontAwesomeIconType.Desktop , "\uf108"},
                { FontAwesomeIconType.Laptop , "\uf109"},
                { FontAwesomeIconType.Tablet , "\uf10a"},
                { FontAwesomeIconType.Mobile , "\uf10b"},
                { FontAwesomeIconType.QuoteLeft , "\uf10d"},
                { FontAwesomeIconType.QuoteRight , "\uf10e"},
                { FontAwesomeIconType.Spinner , "\uf110"},
                { FontAwesomeIconType.Circle , "\uf111"},
                { FontAwesomeIconType.Smile , "\uf118"},
                { FontAwesomeIconType.Frown , "\uf119"},
                { FontAwesomeIconType.Meh , "\uf11a"},
                { FontAwesomeIconType.Gamepad , "\uf11b"},
                { FontAwesomeIconType.Keyboard , "\uf11c"},
                { FontAwesomeIconType.FlagCheckered , "\uf11e"},
                { FontAwesomeIconType.Terminal , "\uf120"},
                { FontAwesomeIconType.Code , "\uf121"},
                { FontAwesomeIconType.ReplyAll , "\uf122"},
                { FontAwesomeIconType.LocationArrow , "\uf124"},
                { FontAwesomeIconType.Crop , "\uf125"},
                { FontAwesomeIconType.CodeBranch , "\uf126"},
                { FontAwesomeIconType.Unlink , "\uf127"},
                { FontAwesomeIconType.Question , "\uf128"},
                { FontAwesomeIconType.Info , "\uf129"},
                { FontAwesomeIconType.Exclamation , "\uf12a"},
                { FontAwesomeIconType.Superscript , "\uf12b"},
                { FontAwesomeIconType.Subscript , "\uf12c"},
                { FontAwesomeIconType.Eraser , "\uf12d"},
                { FontAwesomeIconType.PuzzlePiece , "\uf12e"},
                { FontAwesomeIconType.Microphone , "\uf130"},
                { FontAwesomeIconType.MicrophoneSlash , "\uf131"},
                { FontAwesomeIconType.Calendar , "\uf133"},
                { FontAwesomeIconType.FireExtinguisher , "\uf134"},
                { FontAwesomeIconType.Rocket , "\uf135"},
                { FontAwesomeIconType.ChevronCircleLeft , "\uf137"},
                { FontAwesomeIconType.ChevronCircleRight , "\uf138"},
                { FontAwesomeIconType.ChevronCircleUp , "\uf139"},
                { FontAwesomeIconType.ChevronCircleDown , "\uf13a"},
                { FontAwesomeIconType.Anchor , "\uf13d"},
                { FontAwesomeIconType.UnlockAlt , "\uf13e"},
                { FontAwesomeIconType.Bullseye , "\uf140"},
                { FontAwesomeIconType.EllipsisH , "\uf141"},
                { FontAwesomeIconType.EllipsisV , "\uf142"},
                { FontAwesomeIconType.RssSquare , "\uf143"},
                { FontAwesomeIconType.PlayCircle , "\uf144"},
                { FontAwesomeIconType.MinusSquare , "\uf146"},
                { FontAwesomeIconType.CheckSquare , "\uf14a"},
                { FontAwesomeIconType.PenSquare , "\uf14b"},
                { FontAwesomeIconType.ShareSquare , "\uf14d"},
                { FontAwesomeIconType.Compass , "\uf14e"},
                { FontAwesomeIconType.CaretSquareDown , "\uf150"},
                { FontAwesomeIconType.CaretSquareUp , "\uf151"},
                { FontAwesomeIconType.CaretSquareRight , "\uf152"},
                { FontAwesomeIconType.EuroSign , "\uf153"},
                { FontAwesomeIconType.PoundSign , "\uf154"},
                { FontAwesomeIconType.DollarSign , "\uf155"},
                { FontAwesomeIconType.RupeeSign , "\uf156"},
                { FontAwesomeIconType.YenSign , "\uf157"},
                { FontAwesomeIconType.RubleSign , "\uf158"},
                { FontAwesomeIconType.WonSign , "\uf159"},
                { FontAwesomeIconType.File , "\uf15b"},
                { FontAwesomeIconType.FileAlt , "\uf15c"},
                { FontAwesomeIconType.SortAlphaDown , "\uf15d"},
                { FontAwesomeIconType.SortAlphaUp , "\uf15e"},
                { FontAwesomeIconType.SortAmountDown , "\uf160"},
                { FontAwesomeIconType.SortAmountUp , "\uf161"},
                { FontAwesomeIconType.SortNumericDown , "\uf162"},
                { FontAwesomeIconType.SortNumericUp , "\uf163"},
                { FontAwesomeIconType.ThumbsUp , "\uf164"},
                { FontAwesomeIconType.ThumbsDown , "\uf165"},
                { FontAwesomeIconType.Female , "\uf182"},
                { FontAwesomeIconType.Male , "\uf183"},
                { FontAwesomeIconType.Sun , "\uf185"},
                { FontAwesomeIconType.Moon , "\uf186"},
                { FontAwesomeIconType.Archive , "\uf187"},
                { FontAwesomeIconType.Bug , "\uf188"},
                { FontAwesomeIconType.CaretSquareLeft , "\uf191"},
                { FontAwesomeIconType.DotCircle , "\uf192"},
                { FontAwesomeIconType.Wheelchair , "\uf193"},
                { FontAwesomeIconType.LiraSign , "\uf195"},
                { FontAwesomeIconType.SpaceShuttle , "\uf197"},
                { FontAwesomeIconType.EnvelopeSquare , "\uf199"},
                { FontAwesomeIconType.University , "\uf19c"},
                { FontAwesomeIconType.GraduationCap , "\uf19d"},
                { FontAwesomeIconType.Language , "\uf1ab"},
                { FontAwesomeIconType.Fax , "\uf1ac"},
                { FontAwesomeIconType.Building , "\uf1ad"},
                { FontAwesomeIconType.Child , "\uf1ae"},
                { FontAwesomeIconType.Paw , "\uf1b0"},
                { FontAwesomeIconType.Cube , "\uf1b2"},
                { FontAwesomeIconType.Cubes , "\uf1b3"},
                { FontAwesomeIconType.Recycle , "\uf1b8"},
                { FontAwesomeIconType.Car , "\uf1b9"},
                { FontAwesomeIconType.Taxi , "\uf1ba"},
                { FontAwesomeIconType.Tree , "\uf1bb"},
                { FontAwesomeIconType.Database , "\uf1c0"},
                { FontAwesomeIconType.FilePdf , "\uf1c1"},
                { FontAwesomeIconType.FileWord , "\uf1c2"},
                { FontAwesomeIconType.FileExcel , "\uf1c3"},
                { FontAwesomeIconType.FilePowerpoint , "\uf1c4"},
                { FontAwesomeIconType.FileImage , "\uf1c5"},
                { FontAwesomeIconType.FileArchive , "\uf1c6"},
                { FontAwesomeIconType.FileAudio , "\uf1c7"},
                { FontAwesomeIconType.FileVideo , "\uf1c8"},
                { FontAwesomeIconType.FileCode , "\uf1c9"},
                { FontAwesomeIconType.LifeRing , "\uf1cd"},
                { FontAwesomeIconType.CircleNotch , "\uf1ce"},
                { FontAwesomeIconType.PaperPlane , "\uf1d8"},
                { FontAwesomeIconType.History , "\uf1da"},
                { FontAwesomeIconType.Heading , "\uf1dc"},
                { FontAwesomeIconType.Paragraph , "\uf1dd"},
                { FontAwesomeIconType.SlidersH , "\uf1de"},
                { FontAwesomeIconType.ShareAlt , "\uf1e0"},
                { FontAwesomeIconType.ShareAltSquare , "\uf1e1"},
                { FontAwesomeIconType.Bomb , "\uf1e2"},
                { FontAwesomeIconType.Futbol , "\uf1e3"},
                { FontAwesomeIconType.Tty , "\uf1e4"},
                { FontAwesomeIconType.Binoculars , "\uf1e5"},
                { FontAwesomeIconType.Plug , "\uf1e6"},
                { FontAwesomeIconType.Newspaper , "\uf1ea"},
                { FontAwesomeIconType.Wifi , "\uf1eb"},
                { FontAwesomeIconType.Calculator , "\uf1ec"},
                { FontAwesomeIconType.BellSlash , "\uf1f6"},
                { FontAwesomeIconType.Trash , "\uf1f8"},
                { FontAwesomeIconType.Copyright , "\uf1f9"},
                { FontAwesomeIconType.At , "\uf1fa"},
                { FontAwesomeIconType.EyeDropper , "\uf1fb"},
                { FontAwesomeIconType.PaintBrush , "\uf1fc"},
                { FontAwesomeIconType.BirthdayCake , "\uf1fd"},
                { FontAwesomeIconType.ChartArea , "\uf1fe"},
                { FontAwesomeIconType.ChartPie , "\uf200"},
                { FontAwesomeIconType.ChartLine , "\uf201"},
                { FontAwesomeIconType.ToggleOff , "\uf204"},
                { FontAwesomeIconType.ToggleOn , "\uf205"},
                { FontAwesomeIconType.Bicycle , "\uf206"},
                { FontAwesomeIconType.Bus , "\uf207"},
                { FontAwesomeIconType.ClosedCaptioning , "\uf20a"},
                { FontAwesomeIconType.ShekelSign , "\uf20b"},
                { FontAwesomeIconType.CartPlus , "\uf217"},
                { FontAwesomeIconType.CartArrowDown , "\uf218"},
                { FontAwesomeIconType.Ship , "\uf21a"},
                { FontAwesomeIconType.UserSecret , "\uf21b"},
                { FontAwesomeIconType.Motorcycle , "\uf21c"},
                { FontAwesomeIconType.StreetView , "\uf21d"},
                { FontAwesomeIconType.Heartbeat , "\uf21e"},
                { FontAwesomeIconType.Venus , "\uf221"},
                { FontAwesomeIconType.Mars , "\uf222"},
                { FontAwesomeIconType.Mercury , "\uf223"},
                { FontAwesomeIconType.Transgender , "\uf224"},
                { FontAwesomeIconType.TransgenderAlt , "\uf225"},
                { FontAwesomeIconType.VenusDouble , "\uf226"},
                { FontAwesomeIconType.MarsDouble , "\uf227"},
                { FontAwesomeIconType.VenusMars , "\uf228"},
                { FontAwesomeIconType.MarsStroke , "\uf229"},
                { FontAwesomeIconType.MarsStrokeV , "\uf22a"},
                { FontAwesomeIconType.MarsStrokeH , "\uf22b"},
                { FontAwesomeIconType.Neuter , "\uf22c"},
                { FontAwesomeIconType.Genderless , "\uf22d"},
                { FontAwesomeIconType.Server , "\uf233"},
                { FontAwesomeIconType.UserPlus , "\uf234"},
                { FontAwesomeIconType.UserTimes , "\uf235"},
                { FontAwesomeIconType.Bed , "\uf236"},
                { FontAwesomeIconType.Train , "\uf238"},
                { FontAwesomeIconType.Subway , "\uf239"},
                { FontAwesomeIconType.BatteryFull , "\uf240"},
                { FontAwesomeIconType.BatteryThreeQuarters , "\uf241"},
                { FontAwesomeIconType.BatteryHalf , "\uf242"},
                { FontAwesomeIconType.BatteryQuarter , "\uf243"},
                { FontAwesomeIconType.BatteryEmpty , "\uf244"},
                { FontAwesomeIconType.MousePointer , "\uf245"},
                { FontAwesomeIconType.ICursor , "\uf246"},
                { FontAwesomeIconType.ObjectGroup , "\uf247"},
                { FontAwesomeIconType.ObjectUngroup , "\uf248"},
                { FontAwesomeIconType.StickyNote , "\uf249"},
                { FontAwesomeIconType.Clone , "\uf24d"},
                { FontAwesomeIconType.BalanceScale , "\uf24e"},
                { FontAwesomeIconType.HourglassStart , "\uf251"},
                { FontAwesomeIconType.HourglassHalf , "\uf252"},
                { FontAwesomeIconType.HourglassEnd , "\uf253"},
                { FontAwesomeIconType.Hourglass , "\uf254"},
                { FontAwesomeIconType.HandRock , "\uf255"},
                { FontAwesomeIconType.HandPaper , "\uf256"},
                { FontAwesomeIconType.HandScissors , "\uf257"},
                { FontAwesomeIconType.HandLizard , "\uf258"},
                { FontAwesomeIconType.HandSpock , "\uf259"},
                { FontAwesomeIconType.HandPointer , "\uf25a"},
                { FontAwesomeIconType.HandPeace , "\uf25b"},
                { FontAwesomeIconType.Trademark , "\uf25c"},
                { FontAwesomeIconType.Registered , "\uf25d"},
                { FontAwesomeIconType.Tv , "\uf26c"},
                { FontAwesomeIconType.CalendarPlus , "\uf271"},
                { FontAwesomeIconType.CalendarMinus , "\uf272"},
                { FontAwesomeIconType.CalendarTimes , "\uf273"},
                { FontAwesomeIconType.CalendarCheck , "\uf274"},
                { FontAwesomeIconType.Industry , "\uf275"},
                { FontAwesomeIconType.MapPin , "\uf276"},
                { FontAwesomeIconType.MapSigns , "\uf277"},
                { FontAwesomeIconType.Map , "\uf279"},
                { FontAwesomeIconType.CommentAlt , "\uf27a"},
                { FontAwesomeIconType.PauseCircle , "\uf28b"},
                { FontAwesomeIconType.StopCircle , "\uf28d"},
                { FontAwesomeIconType.ShoppingBag , "\uf290"},
                { FontAwesomeIconType.ShoppingBasket , "\uf291"},
                { FontAwesomeIconType.Hashtag , "\uf292"},
                { FontAwesomeIconType.Percent , "\uf295"},
                { FontAwesomeIconType.UniversalAccess , "\uf29a"},
                { FontAwesomeIconType.Blind , "\uf29d"},
                { FontAwesomeIconType.AudioDescription , "\uf29e"},
                { FontAwesomeIconType.PhoneVolume , "\uf2a0"},
                { FontAwesomeIconType.Braille , "\uf2a1"},
                { FontAwesomeIconType.AssistiveListeningSystems , "\uf2a2"},
                { FontAwesomeIconType.AmericanSignLanguageInterpreting , "\uf2a3"},
                { FontAwesomeIconType.Deaf , "\uf2a4"},
                { FontAwesomeIconType.SignLanguage , "\uf2a7"},
                { FontAwesomeIconType.LowVision , "\uf2a8"},
                { FontAwesomeIconType.Handshake , "\uf2b5"},
                { FontAwesomeIconType.EnvelopeOpen , "\uf2b6"},
                { FontAwesomeIconType.AddressBook , "\uf2b9"},
                { FontAwesomeIconType.AddressCard , "\uf2bb"},
                { FontAwesomeIconType.UserCircle , "\uf2bd"},
                { FontAwesomeIconType.IdBadge , "\uf2c1"},
                { FontAwesomeIconType.IdCard , "\uf2c2"},
                { FontAwesomeIconType.ThermometerFull , "\uf2c7"},
                { FontAwesomeIconType.ThermometerThreeQuarters , "\uf2c8"},
                { FontAwesomeIconType.ThermometerHalf , "\uf2c9"},
                { FontAwesomeIconType.ThermometerQuarter , "\uf2ca"},
                { FontAwesomeIconType.ThermometerEmpty , "\uf2cb"},
                { FontAwesomeIconType.Shower , "\uf2cc"},
                { FontAwesomeIconType.Bath , "\uf2cd"},
                { FontAwesomeIconType.Podcast , "\uf2ce"},
                { FontAwesomeIconType.WindowMaximize , "\uf2d0"},
                { FontAwesomeIconType.WindowMinimize , "\uf2d1"},
                { FontAwesomeIconType.WindowRestore , "\uf2d2"},
                { FontAwesomeIconType.Microchip , "\uf2db"},
                { FontAwesomeIconType.Snowflake , "\uf2dc"},
                { FontAwesomeIconType.UtensilSpoon , "\uf2e5"},
                { FontAwesomeIconType.Utensils , "\uf2e7"},
                { FontAwesomeIconType.UndoAlt , "\uf2ea"},
                { FontAwesomeIconType.TrashAlt , "\uf2ed"},
                { FontAwesomeIconType.SyncAlt , "\uf2f1"},
                { FontAwesomeIconType.Stopwatch , "\uf2f2"},
                { FontAwesomeIconType.SignOutAlt , "\uf2f5"},
                { FontAwesomeIconType.SignInAlt , "\uf2f6"},
                { FontAwesomeIconType.RedoAlt , "\uf2f9"},
                { FontAwesomeIconType.Poo , "\uf2fe"},
                { FontAwesomeIconType.Images , "\uf302"},
                { FontAwesomeIconType.PencilAlt , "\uf303"},
                { FontAwesomeIconType.Pen , "\uf304"},
                { FontAwesomeIconType.PenAlt , "\uf305"},
                { FontAwesomeIconType.LongArrowAltDown , "\uf309"},
                { FontAwesomeIconType.LongArrowAltLeft , "\uf30a"},
                { FontAwesomeIconType.LongArrowAltRight , "\uf30b"},
                { FontAwesomeIconType.LongArrowAltUp , "\uf30c"},
                { FontAwesomeIconType.ExpandArrowsAlt , "\uf31e"},
                { FontAwesomeIconType.Clipboard , "\uf328"},
                { FontAwesomeIconType.ArrowsAltH , "\uf337"},
                { FontAwesomeIconType.ArrowsAltV , "\uf338"},
                { FontAwesomeIconType.ArrowAltCircleDown , "\uf358"},
                { FontAwesomeIconType.ArrowAltCircleLeft , "\uf359"},
                { FontAwesomeIconType.ArrowAltCircleRight , "\uf35a"},
                { FontAwesomeIconType.ArrowAltCircleUp , "\uf35b"},
                { FontAwesomeIconType.ExternalLinkAlt , "\uf35d"},
                { FontAwesomeIconType.ExternalLinkSquareAlt , "\uf360"},
                { FontAwesomeIconType.ExchangeAlt , "\uf362"},
                { FontAwesomeIconType.CloudDownloadAlt , "\uf381"},
                { FontAwesomeIconType.CloudUploadAlt , "\uf382"},
                { FontAwesomeIconType.Gem , "\uf3a5"},
                { FontAwesomeIconType.LevelDownAlt , "\uf3be"},
                { FontAwesomeIconType.LevelUpAlt , "\uf3bf"},
                { FontAwesomeIconType.LockOpen , "\uf3c1"},
                { FontAwesomeIconType.MapMarkerAlt , "\uf3c5"},
                { FontAwesomeIconType.MicrophoneAlt , "\uf3c9"},
                { FontAwesomeIconType.MobileAlt , "\uf3cd"},
                { FontAwesomeIconType.MoneyBillAlt , "\uf3d1"},
                { FontAwesomeIconType.PhoneSlash , "\uf3dd"},
                { FontAwesomeIconType.Portrait , "\uf3e0"},
                { FontAwesomeIconType.Reply , "\uf3e5"},
                { FontAwesomeIconType.ShieldAlt , "\uf3ed"},
                { FontAwesomeIconType.TabletAlt , "\uf3fa"},
                { FontAwesomeIconType.TachometerAlt , "\uf3fd"},
                { FontAwesomeIconType.TicketAlt , "\uf3ff"},
                { FontAwesomeIconType.UserAlt , "\uf406"},
                { FontAwesomeIconType.WindowClose , "\uf410"},
                { FontAwesomeIconType.CompressAlt , "\uf422"},
                { FontAwesomeIconType.ExpandAlt , "\uf424"},
                { FontAwesomeIconType.BaseballBall , "\uf433"},
                { FontAwesomeIconType.BasketballBall , "\uf434"},
                { FontAwesomeIconType.BowlingBall , "\uf436"},
                { FontAwesomeIconType.Chess , "\uf439"},
                { FontAwesomeIconType.ChessBishop , "\uf43a"},
                { FontAwesomeIconType.ChessBoard , "\uf43c"},
                { FontAwesomeIconType.ChessKing , "\uf43f"},
                { FontAwesomeIconType.ChessKnight , "\uf441"},
                { FontAwesomeIconType.ChessPawn , "\uf443"},
                { FontAwesomeIconType.ChessQueen , "\uf445"},
                { FontAwesomeIconType.ChessRook , "\uf447"},
                { FontAwesomeIconType.Dumbbell , "\uf44b"},
                { FontAwesomeIconType.FootballBall , "\uf44e"},
                { FontAwesomeIconType.GolfBall , "\uf450"},
                { FontAwesomeIconType.HockeyPuck , "\uf453"},
                { FontAwesomeIconType.Quidditch , "\uf458"},
                { FontAwesomeIconType.SquareFull , "\uf45c"},
                { FontAwesomeIconType.TableTennis , "\uf45d"},
                { FontAwesomeIconType.VolleyballBall , "\uf45f"},
                { FontAwesomeIconType.Allergies , "\uf461"},
                { FontAwesomeIconType.BandAid , "\uf462"},
                { FontAwesomeIconType.Box , "\uf466"},
                { FontAwesomeIconType.Boxes , "\uf468"},
                { FontAwesomeIconType.BriefcaseMedical , "\uf469"},
                { FontAwesomeIconType.Burn , "\uf46a"},
                { FontAwesomeIconType.Capsules , "\uf46b"},
                { FontAwesomeIconType.ClipboardCheck , "\uf46c"},
                { FontAwesomeIconType.ClipboardList , "\uf46d"},
                { FontAwesomeIconType.Diagnoses , "\uf470"},
                { FontAwesomeIconType.Dna , "\uf471"},
                { FontAwesomeIconType.Dolly , "\uf472"},
                { FontAwesomeIconType.DollyFlatbed , "\uf474"},
                { FontAwesomeIconType.FileMedical , "\uf477"},
                { FontAwesomeIconType.FileMedicalAlt , "\uf478"},
                { FontAwesomeIconType.FirstAid , "\uf479"},
                { FontAwesomeIconType.HospitalAlt , "\uf47d"},
                { FontAwesomeIconType.HospitalSymbol , "\uf47e"},
                { FontAwesomeIconType.IdCardAlt , "\uf47f"},
                { FontAwesomeIconType.NotesMedical , "\uf481"},
                { FontAwesomeIconType.Pallet , "\uf482"},
                { FontAwesomeIconType.Pills , "\uf484"},
                { FontAwesomeIconType.PrescriptionBottle , "\uf485"},
                { FontAwesomeIconType.PrescriptionBottleAlt , "\uf486"},
                { FontAwesomeIconType.Procedures , "\uf487"},
                { FontAwesomeIconType.ShippingFast , "\uf48b"},
                { FontAwesomeIconType.Smoking , "\uf48d"},
                { FontAwesomeIconType.Syringe , "\uf48e"},
                { FontAwesomeIconType.Tablets , "\uf490"},
                { FontAwesomeIconType.Thermometer , "\uf491"},
                { FontAwesomeIconType.Vial , "\uf492"},
                { FontAwesomeIconType.Vials , "\uf493"},
                { FontAwesomeIconType.Warehouse , "\uf494"},
                { FontAwesomeIconType.Weight , "\uf496"},
                { FontAwesomeIconType.XRay , "\uf497"},
                { FontAwesomeIconType.BoxOpen , "\uf49e"},
                { FontAwesomeIconType.CommentDots , "\uf4ad"},
                { FontAwesomeIconType.CommentSlash , "\uf4b3"},
                { FontAwesomeIconType.Couch , "\uf4b8"},
                { FontAwesomeIconType.Donate , "\uf4b9"},
                { FontAwesomeIconType.Dove , "\uf4ba"},
                { FontAwesomeIconType.HandHolding , "\uf4bd"},
                { FontAwesomeIconType.HandHoldingHeart , "\uf4be"},
                { FontAwesomeIconType.HandHoldingUsd , "\uf4c0"},
                { FontAwesomeIconType.HandHoldingWater , "\uf4c1"},
                { FontAwesomeIconType.Hands , "\uf4c2"},
                { FontAwesomeIconType.HandsHelping , "\uf4c4"},
                { FontAwesomeIconType.ParachuteBox , "\uf4cd"},
                { FontAwesomeIconType.PeopleCarry , "\uf4ce"},
                { FontAwesomeIconType.PiggyBank , "\uf4d3"},
                { FontAwesomeIconType.Ribbon , "\uf4d6"},
                { FontAwesomeIconType.Route , "\uf4d7"},
                { FontAwesomeIconType.Seedling , "\uf4d8"},
                { FontAwesomeIconType.Sign , "\uf4d9"},
                { FontAwesomeIconType.SmileWink , "\uf4da"},
                { FontAwesomeIconType.Tape , "\uf4db"},
                { FontAwesomeIconType.TruckLoading , "\uf4de"},
                { FontAwesomeIconType.TruckMoving , "\uf4df"},
                { FontAwesomeIconType.VideoSlash , "\uf4e2"},
                { FontAwesomeIconType.WineGlass , "\uf4e3"},
                { FontAwesomeIconType.FontAwesomeLogoFull , "\uf4e6"},
                { FontAwesomeIconType.UserAltSlash , "\uf4fa"},
                { FontAwesomeIconType.UserAstronaut , "\uf4fb"},
                { FontAwesomeIconType.UserCheck , "\uf4fc"},
                { FontAwesomeIconType.UserClock , "\uf4fd"},
                { FontAwesomeIconType.UserCog , "\uf4fe"},
                { FontAwesomeIconType.UserEdit , "\uf4ff"},
                { FontAwesomeIconType.UserFriends , "\uf500"},
                { FontAwesomeIconType.UserGraduate , "\uf501"},
                { FontAwesomeIconType.UserLock , "\uf502"},
                { FontAwesomeIconType.UserMinus , "\uf503"},
                { FontAwesomeIconType.UserNinja , "\uf504"},
                { FontAwesomeIconType.UserShield , "\uf505"},
                { FontAwesomeIconType.UserSlash , "\uf506"},
                { FontAwesomeIconType.UserTag , "\uf507"},
                { FontAwesomeIconType.UserTie , "\uf508"},
                { FontAwesomeIconType.UsersCog , "\uf509"},
                { FontAwesomeIconType.BalanceScaleLeft , "\uf515"},
                { FontAwesomeIconType.BalanceScaleRight , "\uf516"},
                { FontAwesomeIconType.Blender , "\uf517"},
                { FontAwesomeIconType.BookOpen , "\uf518"},
                { FontAwesomeIconType.BroadcastTower , "\uf519"},
                { FontAwesomeIconType.Broom , "\uf51a"},
                { FontAwesomeIconType.Chalkboard , "\uf51b"},
                { FontAwesomeIconType.ChalkboardTeacher , "\uf51c"},
                { FontAwesomeIconType.Church , "\uf51d"},
                { FontAwesomeIconType.Coins , "\uf51e"},
                { FontAwesomeIconType.CompactDisc , "\uf51f"},
                { FontAwesomeIconType.Crow , "\uf520"},
                { FontAwesomeIconType.Crown , "\uf521"},
                { FontAwesomeIconType.Dice , "\uf522"},
                { FontAwesomeIconType.DiceFive , "\uf523"},
                { FontAwesomeIconType.DiceFour , "\uf524"},
                { FontAwesomeIconType.DiceOne , "\uf525"},
                { FontAwesomeIconType.DiceSix , "\uf526"},
                { FontAwesomeIconType.DiceThree , "\uf527"},
                { FontAwesomeIconType.DiceTwo , "\uf528"},
                { FontAwesomeIconType.Divide , "\uf529"},
                { FontAwesomeIconType.DoorClosed , "\uf52a"},
                { FontAwesomeIconType.DoorOpen , "\uf52b"},
                { FontAwesomeIconType.Equals , "\uf52c"},
                { FontAwesomeIconType.Feather , "\uf52d"},
                { FontAwesomeIconType.Frog , "\uf52e"},
                { FontAwesomeIconType.GasPump , "\uf52f"},
                { FontAwesomeIconType.Glasses , "\uf530"},
                { FontAwesomeIconType.GreaterThan , "\uf531"},
                { FontAwesomeIconType.GreaterThanEqual , "\uf532"},
                { FontAwesomeIconType.Helicopter , "\uf533"},
                { FontAwesomeIconType.Infinity , "\uf534"},
                { FontAwesomeIconType.KiwiBird , "\uf535"},
                { FontAwesomeIconType.LessThan , "\uf536"},
                { FontAwesomeIconType.LessThanEqual , "\uf537"},
                { FontAwesomeIconType.Memory , "\uf538"},
                { FontAwesomeIconType.MicrophoneAltSlash , "\uf539"},
                { FontAwesomeIconType.MoneyBillWave , "\uf53a"},
                { FontAwesomeIconType.MoneyBillWaveAlt , "\uf53b"},
                { FontAwesomeIconType.MoneyCheck , "\uf53c"},
                { FontAwesomeIconType.MoneyCheckAlt , "\uf53d"},
                { FontAwesomeIconType.NotEqual , "\uf53e"},
                { FontAwesomeIconType.Palette , "\uf53f"},
                { FontAwesomeIconType.Parking , "\uf540"},
                { FontAwesomeIconType.Percentage , "\uf541"},
                { FontAwesomeIconType.ProjectDiagram , "\uf542"},
                { FontAwesomeIconType.Receipt , "\uf543"},
                { FontAwesomeIconType.Robot , "\uf544"},
                { FontAwesomeIconType.Ruler , "\uf545"},
                { FontAwesomeIconType.RulerCombined , "\uf546"},
                { FontAwesomeIconType.RulerHorizontal , "\uf547"},
                { FontAwesomeIconType.RulerVertical , "\uf548"},
                { FontAwesomeIconType.School , "\uf549"},
                { FontAwesomeIconType.Screwdriver , "\uf54a"},
                { FontAwesomeIconType.ShoePrints , "\uf54b"},
                { FontAwesomeIconType.Skull , "\uf54c"},
                { FontAwesomeIconType.SmokingBan , "\uf54d"},
                { FontAwesomeIconType.Store , "\uf54e"},
                { FontAwesomeIconType.StoreAlt , "\uf54f"},
                { FontAwesomeIconType.Stream , "\uf550"},
                { FontAwesomeIconType.Stroopwafel , "\uf551"},
                { FontAwesomeIconType.Toolbox , "\uf552"},
                { FontAwesomeIconType.Tshirt , "\uf553"},
                { FontAwesomeIconType.Walking , "\uf554"},
                { FontAwesomeIconType.Wallet , "\uf555"},
                { FontAwesomeIconType.Angry , "\uf556"},
                { FontAwesomeIconType.Archway , "\uf557"},
                { FontAwesomeIconType.Atlas , "\uf558"},
                { FontAwesomeIconType.Award , "\uf559"},
                { FontAwesomeIconType.Backspace , "\uf55a"},
                { FontAwesomeIconType.BezierCurve , "\uf55b"},
                { FontAwesomeIconType.Bong , "\uf55c"},
                { FontAwesomeIconType.Brush , "\uf55d"},
                { FontAwesomeIconType.BusAlt , "\uf55e"},
                { FontAwesomeIconType.Cannabis , "\uf55f"},
                { FontAwesomeIconType.CheckDouble , "\uf560"},
                { FontAwesomeIconType.Cocktail , "\uf561"},
                { FontAwesomeIconType.ConciergeBell , "\uf562"},
                { FontAwesomeIconType.Cookie , "\uf563"},
                { FontAwesomeIconType.CookieBite , "\uf564"},
                { FontAwesomeIconType.CropAlt , "\uf565"},
                { FontAwesomeIconType.DigitalTachograph , "\uf566"},
                { FontAwesomeIconType.Dizzy , "\uf567"},
                { FontAwesomeIconType.DraftingCompass , "\uf568"},
                { FontAwesomeIconType.Drum , "\uf569"},
                { FontAwesomeIconType.DrumSteelpan , "\uf56a"},
                { FontAwesomeIconType.FeatherAlt , "\uf56b"},
                { FontAwesomeIconType.FileContract , "\uf56c"},
                { FontAwesomeIconType.FileDownload , "\uf56d"},
                { FontAwesomeIconType.FileExport , "\uf56e"},
                { FontAwesomeIconType.FileImport , "\uf56f"},
                { FontAwesomeIconType.FileInvoice , "\uf570"},
                { FontAwesomeIconType.FileInvoiceDollar , "\uf571"},
                { FontAwesomeIconType.FilePrescription , "\uf572"},
                { FontAwesomeIconType.FileSignature , "\uf573"},
                { FontAwesomeIconType.FileUpload , "\uf574"},
                { FontAwesomeIconType.Fill , "\uf575"},
                { FontAwesomeIconType.FillDrip , "\uf576"},
                { FontAwesomeIconType.Fingerprint , "\uf577"},
                { FontAwesomeIconType.Fish , "\uf578"},
                { FontAwesomeIconType.Flushed , "\uf579"},
                { FontAwesomeIconType.FrownOpen , "\uf57a"},
                { FontAwesomeIconType.GlassMartiniAlt , "\uf57b"},
                { FontAwesomeIconType.GlobeAfrica , "\uf57c"},
                { FontAwesomeIconType.GlobeAmericas , "\uf57d"},
                { FontAwesomeIconType.GlobeAsia , "\uf57e"},
                { FontAwesomeIconType.Grimace , "\uf57f"},
                { FontAwesomeIconType.Grin , "\uf580"},
                { FontAwesomeIconType.GrinAlt , "\uf581"},
                { FontAwesomeIconType.GrinBeam , "\uf582"},
                { FontAwesomeIconType.GrinBeamSweat , "\uf583"},
                { FontAwesomeIconType.GrinHearts , "\uf584"},
                { FontAwesomeIconType.GrinSquint , "\uf585"},
                { FontAwesomeIconType.GrinSquintTears , "\uf586"},
                { FontAwesomeIconType.GrinStars , "\uf587"},
                { FontAwesomeIconType.GrinTears , "\uf588"},
                { FontAwesomeIconType.GrinTongue , "\uf589"},
                { FontAwesomeIconType.GrinTongueSquint , "\uf58a"},
                { FontAwesomeIconType.GrinTongueWink , "\uf58b"},
                { FontAwesomeIconType.GrinWink , "\uf58c"},
                { FontAwesomeIconType.GripHorizontal , "\uf58d"},
                { FontAwesomeIconType.GripVertical , "\uf58e"},
                { FontAwesomeIconType.HeadphonesAlt , "\uf58f"},
                { FontAwesomeIconType.Headset , "\uf590"},
                { FontAwesomeIconType.Highlighter , "\uf591"},
                { FontAwesomeIconType.HotTub , "\uf593"},
                { FontAwesomeIconType.Hotel , "\uf594"},
                { FontAwesomeIconType.Joint , "\uf595"},
                { FontAwesomeIconType.Kiss , "\uf596"},
                { FontAwesomeIconType.KissBeam , "\uf597"},
                { FontAwesomeIconType.KissWinkHeart , "\uf598"},
                { FontAwesomeIconType.Laugh , "\uf599"},
                { FontAwesomeIconType.LaughBeam , "\uf59a"},
                { FontAwesomeIconType.LaughSquint , "\uf59b"},
                { FontAwesomeIconType.LaughWink , "\uf59c"},
                { FontAwesomeIconType.LuggageCart , "\uf59d"},
                { FontAwesomeIconType.MapMarked , "\uf59f"},
                { FontAwesomeIconType.MapMarkedAlt , "\uf5a0"},
                { FontAwesomeIconType.Marker , "\uf5a1"},
                { FontAwesomeIconType.Medal , "\uf5a2"},
                { FontAwesomeIconType.MehBlank , "\uf5a4"},
                { FontAwesomeIconType.MehRollingEyes , "\uf5a5"},
                { FontAwesomeIconType.Monument , "\uf5a6"},
                { FontAwesomeIconType.MortarPestle , "\uf5a7"},
                { FontAwesomeIconType.PaintRoller , "\uf5aa"},
                { FontAwesomeIconType.Passport , "\uf5ab"},
                { FontAwesomeIconType.PenFancy , "\uf5ac"},
                { FontAwesomeIconType.PenNib , "\uf5ad"},
                { FontAwesomeIconType.PencilRuler , "\uf5ae"},
                { FontAwesomeIconType.PlaneArrival , "\uf5af"},
                { FontAwesomeIconType.PlaneDeparture , "\uf5b0"},
                { FontAwesomeIconType.Prescription , "\uf5b1"},
                { FontAwesomeIconType.SadCry , "\uf5b3"},
                { FontAwesomeIconType.SadTear , "\uf5b4"},
                { FontAwesomeIconType.ShuttleVan , "\uf5b6"},
                { FontAwesomeIconType.Signature , "\uf5b7"},
                { FontAwesomeIconType.SmileBeam , "\uf5b8"},
                { FontAwesomeIconType.SolarPanel , "\uf5ba"},
                { FontAwesomeIconType.Spa , "\uf5bb"},
                { FontAwesomeIconType.Splotch , "\uf5bc"},
                { FontAwesomeIconType.SprayCan , "\uf5bd"},
                { FontAwesomeIconType.Stamp , "\uf5bf"},
                { FontAwesomeIconType.StarHalfAlt , "\uf5c0"},
                { FontAwesomeIconType.SuitcaseRolling , "\uf5c1"},
                { FontAwesomeIconType.Surprise , "\uf5c2"},
                { FontAwesomeIconType.Swatchbook , "\uf5c3"},
                { FontAwesomeIconType.Swimmer , "\uf5c4"},
                { FontAwesomeIconType.SwimmingPool , "\uf5c5"},
                { FontAwesomeIconType.TintSlash , "\uf5c7"},
                { FontAwesomeIconType.Tired , "\uf5c8"},
                { FontAwesomeIconType.Tooth , "\uf5c9"},
                { FontAwesomeIconType.UmbrellaBeach , "\uf5ca"},
                { FontAwesomeIconType.VectorSquare , "\uf5cb"},
                { FontAwesomeIconType.WeightHanging , "\uf5cd"},
                { FontAwesomeIconType.WineGlassAlt , "\uf5ce"},
                { FontAwesomeIconType.AirFreshener , "\uf5d0"},
                { FontAwesomeIconType.AppleAlt , "\uf5d1"},
                { FontAwesomeIconType.Atom , "\uf5d2"},
                { FontAwesomeIconType.Bone , "\uf5d7"},
                { FontAwesomeIconType.BookReader , "\uf5da"},
                { FontAwesomeIconType.Brain , "\uf5dc"},
                { FontAwesomeIconType.CarAlt , "\uf5de"},
                { FontAwesomeIconType.CarBattery , "\uf5df"},
                { FontAwesomeIconType.CarCrash , "\uf5e1"},
                { FontAwesomeIconType.CarSide , "\uf5e4"},
                { FontAwesomeIconType.ChargingStation , "\uf5e7"},
                { FontAwesomeIconType.Directions , "\uf5eb"},
                { FontAwesomeIconType.DrawPolygon , "\uf5ee"},
                { FontAwesomeIconType.LaptopCode , "\uf5fc"},
                { FontAwesomeIconType.LayerGroup , "\uf5fd"},
                { FontAwesomeIconType.Lungs , "\uf604"},
                { FontAwesomeIconType.Microscope , "\uf610"},
                { FontAwesomeIconType.OilCan , "\uf613"},
                { FontAwesomeIconType.Poop , "\uf619"},
                { FontAwesomeIconType.Shapes , "\uf61f"},
                { FontAwesomeIconType.StarOfLife , "\uf621"},
                { FontAwesomeIconType.Teeth , "\uf62e"},
                { FontAwesomeIconType.TeethOpen , "\uf62f"},
                { FontAwesomeIconType.TheaterMasks , "\uf630"},
                { FontAwesomeIconType.TrafficLight , "\uf637"},
                { FontAwesomeIconType.TruckMonster , "\uf63b"},
                { FontAwesomeIconType.TruckPickup , "\uf63c"},
                { FontAwesomeIconType.Ad , "\uf641"},
                { FontAwesomeIconType.Ankh , "\uf644"},
                { FontAwesomeIconType.Bible , "\uf647"},
                { FontAwesomeIconType.BusinessTime , "\uf64a"},
                { FontAwesomeIconType.City , "\uf64f"},
                { FontAwesomeIconType.CommentDollar , "\uf651"},
                { FontAwesomeIconType.CommentsDollar , "\uf653"},
                { FontAwesomeIconType.Cross , "\uf654"},
                { FontAwesomeIconType.Dharmachakra , "\uf655"},
                { FontAwesomeIconType.EnvelopeOpenText , "\uf658"},
                { FontAwesomeIconType.FolderMinus , "\uf65d"},
                { FontAwesomeIconType.FolderPlus , "\uf65e"},
                { FontAwesomeIconType.FunnelDollar , "\uf662"},
                { FontAwesomeIconType.Gopuram , "\uf664"},
                { FontAwesomeIconType.Hamsa , "\uf665"},
                { FontAwesomeIconType.Bahai , "\uf666"},
                { FontAwesomeIconType.Jedi , "\uf669"},
                { FontAwesomeIconType.JournalWhills , "\uf66a"},
                { FontAwesomeIconType.Kaaba , "\uf66b"},
                { FontAwesomeIconType.Khanda , "\uf66d"},
                { FontAwesomeIconType.Landmark , "\uf66f"},
                { FontAwesomeIconType.MailBulk , "\uf674"},
                { FontAwesomeIconType.Menorah , "\uf676"},
                { FontAwesomeIconType.Mosque , "\uf678"},
                { FontAwesomeIconType.Om , "\uf679"},
                { FontAwesomeIconType.Pastafarianism , "\uf67b"},
                { FontAwesomeIconType.Peace , "\uf67c"},
                { FontAwesomeIconType.PlaceOfWorship , "\uf67f"},
                { FontAwesomeIconType.Poll , "\uf681"},
                { FontAwesomeIconType.PollH , "\uf682"},
                { FontAwesomeIconType.Pray , "\uf683"},
                { FontAwesomeIconType.PrayingHands , "\uf684"},
                { FontAwesomeIconType.Quran , "\uf687"},
                { FontAwesomeIconType.SearchDollar , "\uf688"},
                { FontAwesomeIconType.SearchLocation , "\uf689"},
                { FontAwesomeIconType.Socks , "\uf696"},
                { FontAwesomeIconType.SquareRootAlt , "\uf698"},
                { FontAwesomeIconType.StarAndCrescent , "\uf699"},
                { FontAwesomeIconType.StarOfDavid , "\uf69a"},
                { FontAwesomeIconType.Synagogue , "\uf69b"},
                { FontAwesomeIconType.Torah , "\uf6a0"},
                { FontAwesomeIconType.ToriiGate , "\uf6a1"},
                { FontAwesomeIconType.Vihara , "\uf6a7"},
                { FontAwesomeIconType.VolumeMute , "\uf6a9"},
                { FontAwesomeIconType.YinYang , "\uf6ad"},
                { FontAwesomeIconType.BlenderPhone , "\uf6b6"},
                { FontAwesomeIconType.BookDead , "\uf6b7"},
                { FontAwesomeIconType.Campground , "\uf6bb"},
                { FontAwesomeIconType.Cat , "\uf6be"},
                { FontAwesomeIconType.Chair , "\uf6c0"},
                { FontAwesomeIconType.CloudMoon , "\uf6c3"},
                { FontAwesomeIconType.CloudSun , "\uf6c4"},
                { FontAwesomeIconType.DiceD20 , "\uf6cf"},
                { FontAwesomeIconType.DiceD6 , "\uf6d1"},
                { FontAwesomeIconType.Dog , "\uf6d3"},
                { FontAwesomeIconType.Dragon , "\uf6d5"},
                { FontAwesomeIconType.DrumstickBite , "\uf6d7"},
                { FontAwesomeIconType.Dungeon , "\uf6d9"},
                { FontAwesomeIconType.FileCsv , "\uf6dd"},
                { FontAwesomeIconType.FistRaised , "\uf6de"},
                { FontAwesomeIconType.Ghost , "\uf6e2"},
                { FontAwesomeIconType.Hammer , "\uf6e3"},
                { FontAwesomeIconType.Hanukiah , "\uf6e6"},
                { FontAwesomeIconType.HatWizard , "\uf6e8"},
                { FontAwesomeIconType.Hiking , "\uf6ec"},
                { FontAwesomeIconType.Hippo , "\uf6ed"},
                { FontAwesomeIconType.Horse , "\uf6f0"},
                { FontAwesomeIconType.HouseDamage , "\uf6f1"},
                { FontAwesomeIconType.Hryvnia , "\uf6f2"},
                { FontAwesomeIconType.Mask , "\uf6fa"},
                { FontAwesomeIconType.Mountain , "\uf6fc"},
                { FontAwesomeIconType.NetworkWired , "\uf6ff"},
                { FontAwesomeIconType.Otter , "\uf700"},
                { FontAwesomeIconType.Ring , "\uf70b"},
                { FontAwesomeIconType.Running , "\uf70c"},
                { FontAwesomeIconType.Scroll , "\uf70e"},
                { FontAwesomeIconType.SkullCrossbones , "\uf714"},
                { FontAwesomeIconType.Slash , "\uf715"},
                { FontAwesomeIconType.Spider , "\uf717"},
                { FontAwesomeIconType.ToiletPaper , "\uf71e"},
                { FontAwesomeIconType.Tractor , "\uf722"},
                { FontAwesomeIconType.UserInjured , "\uf728"},
                { FontAwesomeIconType.VrCardboard , "\uf729"},
                { FontAwesomeIconType.Wind , "\uf72e"},
                { FontAwesomeIconType.WineBottle , "\uf72f"},
                { FontAwesomeIconType.CloudMeatball , "\uf73b"},
                { FontAwesomeIconType.CloudMoonRain , "\uf73c"},
                { FontAwesomeIconType.CloudRain , "\uf73d"},
                { FontAwesomeIconType.CloudShowersHeavy , "\uf740"},
                { FontAwesomeIconType.CloudSunRain , "\uf743"},
                { FontAwesomeIconType.Democrat , "\uf747"},
                { FontAwesomeIconType.FlagUsa , "\uf74d"},
                { FontAwesomeIconType.Meteor , "\uf753"},
                { FontAwesomeIconType.PersonBooth , "\uf756"},
                { FontAwesomeIconType.PooStorm , "\uf75a"},
                { FontAwesomeIconType.Rainbow , "\uf75b"},
                { FontAwesomeIconType.Republican , "\uf75e"},
                { FontAwesomeIconType.Smog , "\uf75f"},
                { FontAwesomeIconType.TemperatureHigh , "\uf769"},
                { FontAwesomeIconType.TemperatureLow , "\uf76b"},
                { FontAwesomeIconType.VoteYea , "\uf772"},
                { FontAwesomeIconType.Water , "\uf773"},
                { FontAwesomeIconType.Baby , "\uf77c"},
                { FontAwesomeIconType.BabyCarriage , "\uf77d"},
                { FontAwesomeIconType.Biohazard , "\uf780"},
                { FontAwesomeIconType.Blog , "\uf781"},
                { FontAwesomeIconType.CalendarDay , "\uf783"},
                { FontAwesomeIconType.CalendarWeek , "\uf784"},
                { FontAwesomeIconType.CandyCane , "\uf786"},
                { FontAwesomeIconType.Carrot , "\uf787"},
                { FontAwesomeIconType.CashRegister , "\uf788"},
                { FontAwesomeIconType.CompressArrowsAlt , "\uf78c"},
                { FontAwesomeIconType.Dumpster , "\uf793"},
                { FontAwesomeIconType.DumpsterFire , "\uf794"},
                { FontAwesomeIconType.Ethernet , "\uf796"},
                { FontAwesomeIconType.Gifts , "\uf79c"},
                { FontAwesomeIconType.GlassCheers , "\uf79f"},
                { FontAwesomeIconType.GlassWhiskey , "\uf7a0"},
                { FontAwesomeIconType.GlobeEurope , "\uf7a2"},
                { FontAwesomeIconType.GripLines , "\uf7a4"},
                { FontAwesomeIconType.GripLinesVertical , "\uf7a5"},
                { FontAwesomeIconType.Guitar , "\uf7a6"},
                { FontAwesomeIconType.HeartBroken , "\uf7a9"},
                { FontAwesomeIconType.HollyBerry , "\uf7aa"},
                { FontAwesomeIconType.HorseHead , "\uf7ab"},
                { FontAwesomeIconType.Icicles , "\uf7ad"},
                { FontAwesomeIconType.Igloo , "\uf7ae"},
                { FontAwesomeIconType.Mitten , "\uf7b5"},
                { FontAwesomeIconType.MugHot , "\uf7b6"},
                { FontAwesomeIconType.Radiation , "\uf7b9"},
                { FontAwesomeIconType.RadiationAlt , "\uf7ba"},
                { FontAwesomeIconType.Restroom , "\uf7bd"},
                { FontAwesomeIconType.Satellite , "\uf7bf"},
                { FontAwesomeIconType.SatelliteDish , "\uf7c0"},
                { FontAwesomeIconType.SdCard , "\uf7c2"},
                { FontAwesomeIconType.SimCard , "\uf7c4"},
                { FontAwesomeIconType.Skating , "\uf7c5"},
                { FontAwesomeIconType.Skiing , "\uf7c9"},
                { FontAwesomeIconType.SkiingNordic , "\uf7ca"},
                { FontAwesomeIconType.Sleigh , "\uf7cc"},
                { FontAwesomeIconType.Sms , "\uf7cd"},
                { FontAwesomeIconType.Snowboarding , "\uf7ce"},
                { FontAwesomeIconType.Snowman , "\uf7d0"},
                { FontAwesomeIconType.Snowplow , "\uf7d2"},
                { FontAwesomeIconType.Tenge , "\uf7d7"},
                { FontAwesomeIconType.Toilet , "\uf7d8"},
                { FontAwesomeIconType.Tools , "\uf7d9"},
                { FontAwesomeIconType.Tram , "\uf7da"},
                { FontAwesomeIconType.FireAlt , "\uf7e4"},
                { FontAwesomeIconType.Bacon , "\uf7e5"},
                { FontAwesomeIconType.BookMedical , "\uf7e6"},
                { FontAwesomeIconType.BreadSlice , "\uf7ec"},
                { FontAwesomeIconType.Cheese , "\uf7ef"},
                { FontAwesomeIconType.ClinicMedical , "\uf7f2"},
                { FontAwesomeIconType.CommentMedical , "\uf7f5"},
                { FontAwesomeIconType.Crutch , "\uf7f7"},
                { FontAwesomeIconType.Disease , "\uf7fa"},
                { FontAwesomeIconType.Egg , "\uf7fb"},
                { FontAwesomeIconType.Hamburger , "\uf805"},
                { FontAwesomeIconType.HandMiddleFinger , "\uf806"},
                { FontAwesomeIconType.HardHat , "\uf807"},
                { FontAwesomeIconType.HospitalUser , "\uf80d"},
                { FontAwesomeIconType.Hotdog , "\uf80f"},
                { FontAwesomeIconType.IceCream , "\uf810"},
                { FontAwesomeIconType.LaptopMedical , "\uf812"},
                { FontAwesomeIconType.Pager , "\uf815"},
                { FontAwesomeIconType.PepperHot , "\uf816"},
                { FontAwesomeIconType.PizzaSlice , "\uf818"},
                { FontAwesomeIconType.TrashRestore , "\uf829"},
                { FontAwesomeIconType.TrashRestoreAlt , "\uf82a"},
                { FontAwesomeIconType.UserNurse , "\uf82f"},
                { FontAwesomeIconType.WaveSquare , "\uf83e"},
                { FontAwesomeIconType.Biking , "\uf84a"},
                { FontAwesomeIconType.BorderAll , "\uf84c"},
                { FontAwesomeIconType.BorderNone , "\uf850"},
                { FontAwesomeIconType.BorderStyle , "\uf853"},
                { FontAwesomeIconType.Fan , "\uf863"},
                { FontAwesomeIconType.Icons , "\uf86d"},
                { FontAwesomeIconType.PhoneAlt , "\uf879"},
                { FontAwesomeIconType.PhoneSquareAlt , "\uf87b"},
                { FontAwesomeIconType.PhotoVideo , "\uf87c"},
                { FontAwesomeIconType.RemoveFormat , "\uf87d"},
                { FontAwesomeIconType.SortAlphaDownAlt , "\uf881"},
                { FontAwesomeIconType.SortAlphaUpAlt , "\uf882"},
                { FontAwesomeIconType.SortAmountDownAlt , "\uf884"},
                { FontAwesomeIconType.SortAmountUpAlt , "\uf885"},
                { FontAwesomeIconType.SortNumericDownAlt , "\uf886"},
                { FontAwesomeIconType.SortNumericUpAlt , "\uf887"},
                { FontAwesomeIconType.SpellCheck , "\uf891"},
                { FontAwesomeIconType.Voicemail , "\uf897"},
                { FontAwesomeIconType.HatCowboy , "\uf8c0"},
                { FontAwesomeIconType.HatCowboySide , "\uf8c1"},
                { FontAwesomeIconType.Mouse , "\uf8cc"},
                { FontAwesomeIconType.RecordVinyl , "\uf8d9"},
                { FontAwesomeIconType.Caravan , "\uf8ff"},
                { FontAwesomeIconType.Faucet , "\uf905"},
                { FontAwesomeIconType.Trailer , "\uf941"},
                { FontAwesomeIconType.BoxTissue , "\uf95b"},
                { FontAwesomeIconType.HandHoldingMedical , "\uf95c"},
                { FontAwesomeIconType.HandSparkles , "\uf95d"},
                { FontAwesomeIconType.HandsWash , "\uf95e"},
                { FontAwesomeIconType.HandshakeAltSlash , "\uf95f"},
                { FontAwesomeIconType.HandshakeSlash , "\uf960"},
                { FontAwesomeIconType.HeadSideCough , "\uf961"},
                { FontAwesomeIconType.HeadSideCoughSlash , "\uf962"},
                { FontAwesomeIconType.HeadSideMask , "\uf963"},
                { FontAwesomeIconType.HeadSideVirus , "\uf964"},
                { FontAwesomeIconType.HouseUser , "\uf965"},
                { FontAwesomeIconType.LaptopHouse , "\uf966"},
                { FontAwesomeIconType.LungsVirus , "\uf967"},
                { FontAwesomeIconType.PeopleArrows , "\uf968"},
                { FontAwesomeIconType.PlaneSlash , "\uf969"},
                { FontAwesomeIconType.PumpMedical , "\uf96a"},
                { FontAwesomeIconType.PumpSoap , "\uf96b"},
                { FontAwesomeIconType.ShieldVirus , "\uf96c"},
                { FontAwesomeIconType.Soap , "\uf96e"},
                { FontAwesomeIconType.Stopwatch20 , "\uf96f"},
                { FontAwesomeIconType.StoreAltSlash , "\uf970"},
                { FontAwesomeIconType.StoreSlash , "\uf971"},
                { FontAwesomeIconType.ToiletPaperSlash , "\uf972"},
                { FontAwesomeIconType.Virus , "\uf974"},
                { FontAwesomeIconType.VirusSlash , "\uf975"},
                { FontAwesomeIconType.Viruses , "\uf976"}
            };
    }
    public enum FontAwesomeIconType
    {
        GlassMartini,
        Music,
        Search,
        Heart,
        Star,
        User,
        Film,
        ThLarge,
        Th,
        ThList,
        Check,
        Times,
        SearchPlus,
        SearchMinus,
        PowerOff,
        Signal,
        Cog,
        Home,
        Clock,
        Road,
        Download,
        Inbox,
        Redo,
        Sync,
        ListAlt,
        Lock,
        Flag,
        Headphones,
        VolumeOff,
        VolumeDown,
        VolumeUp,
        Qrcode,
        Barcode,
        Tag,
        Tags,
        Book,
        Bookmark,
        Print,
        Camera,
        Font,
        Bold,
        Italic,
        TextHeight,
        TextWidth,
        AlignLeft,
        AlignCenter,
        AlignRight,
        AlignJustify,
        List,
        Outdent,
        Indent,
        Video,
        Image,
        MapMarker,
        Adjust,
        Tint,
        Edit,
        StepBackward,
        FastBackward,
        Backward,
        Play,
        Pause,
        Stop,
        Forward,
        FastForward,
        StepForward,
        Eject,
        ChevronLeft,
        ChevronRight,
        PlusCircle,
        MinusCircle,
        TimesCircle,
        CheckCircle,
        QuestionCircle,
        InfoCircle,
        Crosshairs,
        Ban,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        ArrowDown,
        Share,
        Expand,
        Compress,
        Plus,
        Minus,
        Asterisk,
        ExclamationCircle,
        Gift,
        Leaf,
        Fire,
        Eye,
        EyeSlash,
        ExclamationTriangle,
        Plane,
        CalendarAlt,
        Random,
        Comment,
        Magnet,
        ChevronUp,
        ChevronDown,
        Retweet,
        ShoppingCart,
        Folder,
        FolderOpen,
        ChartBar,
        CameraRetro,
        Key,
        Cogs,
        Comments,
        StarHalf,
        Thumbtack,
        Trophy,
        Upload,
        Lemon,
        Phone,
        PhoneSquare,
        Unlock,
        CreditCard,
        Rss,
        Hdd,
        Bullhorn,
        Certificate,
        HandPointRight,
        HandPointLeft,
        HandPointUp,
        HandPointDown,
        ArrowCircleLeft,
        ArrowCircleRight,
        ArrowCircleUp,
        ArrowCircleDown,
        Globe,
        Wrench,
        Tasks,
        Filter,
        Briefcase,
        ArrowsAlt,
        Users,
        Link,
        Cloud,
        Flask,
        Cut,
        Copy,
        Paperclip,
        Save,
        Square,
        Bars,
        ListUl,
        ListOl,
        Strikethrough,
        Underline,
        Table,
        Magic,
        Truck,
        MoneyBill,
        CaretDown,
        CaretUp,
        CaretLeft,
        CaretRight,
        Columns,
        Sort,
        SortDown,
        SortUp,
        Envelope,
        Undo,
        Gavel,
        Bolt,
        Sitemap,
        Umbrella,
        Paste,
        Lightbulb,
        UserMd,
        Stethoscope,
        Suitcase,
        Bell,
        Coffee,
        Hospital,
        Ambulance,
        Medkit,
        FighterJet,
        Beer,
        HSquare,
        PlusSquare,
        AngleDoubleLeft,
        AngleDoubleRight,
        AngleDoubleUp,
        AngleDoubleDown,
        AngleLeft,
        AngleRight,
        AngleUp,
        AngleDown,
        Desktop,
        Laptop,
        Tablet,
        Mobile,
        QuoteLeft,
        QuoteRight,
        Spinner,
        Circle,
        Smile,
        Frown,
        Meh,
        Gamepad,
        Keyboard,
        FlagCheckered,
        Terminal,
        Code,
        ReplyAll,
        LocationArrow,
        Crop,
        CodeBranch,
        Unlink,
        Question,
        Info,
        Exclamation,
        Superscript,
        Subscript,
        Eraser,
        PuzzlePiece,
        Microphone,
        MicrophoneSlash,
        Calendar,
        FireExtinguisher,
        Rocket,
        ChevronCircleLeft,
        ChevronCircleRight,
        ChevronCircleUp,
        ChevronCircleDown,
        Anchor,
        UnlockAlt,
        Bullseye,
        EllipsisH,
        EllipsisV,
        RssSquare,
        PlayCircle,
        MinusSquare,
        CheckSquare,
        PenSquare,
        ShareSquare,
        Compass,
        CaretSquareDown,
        CaretSquareUp,
        CaretSquareRight,
        EuroSign,
        PoundSign,
        DollarSign,
        RupeeSign,
        YenSign,
        RubleSign,
        WonSign,
        File,
        FileAlt,
        SortAlphaDown,
        SortAlphaUp,
        SortAmountDown,
        SortAmountUp,
        SortNumericDown,
        SortNumericUp,
        ThumbsUp,
        ThumbsDown,
        Female,
        Male,
        Sun,
        Moon,
        Archive,
        Bug,
        CaretSquareLeft,
        DotCircle,
        Wheelchair,
        LiraSign,
        SpaceShuttle,
        EnvelopeSquare,
        University,
        GraduationCap,
        Language,
        Fax,
        Building,
        Child,
        Paw,
        Cube,
        Cubes,
        Recycle,
        Car,
        Taxi,
        Tree,
        Database,
        FilePdf,
        FileWord,
        FileExcel,
        FilePowerpoint,
        FileImage,
        FileArchive,
        FileAudio,
        FileVideo,
        FileCode,
        LifeRing,
        CircleNotch,
        PaperPlane,
        History,
        Heading,
        Paragraph,
        SlidersH,
        ShareAlt,
        ShareAltSquare,
        Bomb,
        Futbol,
        Tty,
        Binoculars,
        Plug,
        Newspaper,
        Wifi,
        Calculator,
        BellSlash,
        Trash,
        Copyright,
        At,
        EyeDropper,
        PaintBrush,
        BirthdayCake,
        ChartArea,
        ChartPie,
        ChartLine,
        ToggleOff,
        ToggleOn,
        Bicycle,
        Bus,
        ClosedCaptioning,
        ShekelSign,
        CartPlus,
        CartArrowDown,
        Ship,
        UserSecret,
        Motorcycle,
        StreetView,
        Heartbeat,
        Venus,
        Mars,
        Mercury,
        Transgender,
        TransgenderAlt,
        VenusDouble,
        MarsDouble,
        VenusMars,
        MarsStroke,
        MarsStrokeV,
        MarsStrokeH,
        Neuter,
        Genderless,
        Server,
        UserPlus,
        UserTimes,
        Bed,
        Train,
        Subway,
        BatteryFull,
        BatteryThreeQuarters,
        BatteryHalf,
        BatteryQuarter,
        BatteryEmpty,
        MousePointer,
        ICursor,
        ObjectGroup,
        ObjectUngroup,
        StickyNote,
        Clone,
        BalanceScale,
        HourglassStart,
        HourglassHalf,
        HourglassEnd,
        Hourglass,
        HandRock,
        HandPaper,
        HandScissors,
        HandLizard,
        HandSpock,
        HandPointer,
        HandPeace,
        Trademark,
        Registered,
        Tv,
        CalendarPlus,
        CalendarMinus,
        CalendarTimes,
        CalendarCheck,
        Industry,
        MapPin,
        MapSigns,
        Map,
        CommentAlt,
        PauseCircle,
        StopCircle,
        ShoppingBag,
        ShoppingBasket,
        Hashtag,
        Percent,
        UniversalAccess,
        Blind,
        AudioDescription,
        PhoneVolume,
        Braille,
        AssistiveListeningSystems,
        AmericanSignLanguageInterpreting,
        Deaf,
        SignLanguage,
        LowVision,
        Handshake,
        EnvelopeOpen,
        AddressBook,
        AddressCard,
        UserCircle,
        IdBadge,
        IdCard,
        ThermometerFull,
        ThermometerThreeQuarters,
        ThermometerHalf,
        ThermometerQuarter,
        ThermometerEmpty,
        Shower,
        Bath,
        Podcast,
        WindowMaximize,
        WindowMinimize,
        WindowRestore,
        Microchip,
        Snowflake,
        UtensilSpoon,
        Utensils,
        UndoAlt,
        TrashAlt,
        SyncAlt,
        Stopwatch,
        SignOutAlt,
        SignInAlt,
        RedoAlt,
        Poo,
        Images,
        PencilAlt,
        Pen,
        PenAlt,
        LongArrowAltDown,
        LongArrowAltLeft,
        LongArrowAltRight,
        LongArrowAltUp,
        ExpandArrowsAlt,
        Clipboard,
        ArrowsAltH,
        ArrowsAltV,
        ArrowAltCircleDown,
        ArrowAltCircleLeft,
        ArrowAltCircleRight,
        ArrowAltCircleUp,
        ExternalLinkAlt,
        ExternalLinkSquareAlt,
        ExchangeAlt,
        CloudDownloadAlt,
        CloudUploadAlt,
        Gem,
        LevelDownAlt,
        LevelUpAlt,
        LockOpen,
        MapMarkerAlt,
        MicrophoneAlt,
        MobileAlt,
        MoneyBillAlt,
        PhoneSlash,
        Portrait,
        Reply,
        ShieldAlt,
        TabletAlt,
        TachometerAlt,
        TicketAlt,
        UserAlt,
        WindowClose,
        CompressAlt,
        ExpandAlt,
        BaseballBall,
        BasketballBall,
        BowlingBall,
        Chess,
        ChessBishop,
        ChessBoard,
        ChessKing,
        ChessKnight,
        ChessPawn,
        ChessQueen,
        ChessRook,
        Dumbbell,
        FootballBall,
        GolfBall,
        HockeyPuck,
        Quidditch,
        SquareFull,
        TableTennis,
        VolleyballBall,
        Allergies,
        BandAid,
        Box,
        Boxes,
        BriefcaseMedical,
        Burn,
        Capsules,
        ClipboardCheck,
        ClipboardList,
        Diagnoses,
        Dna,
        Dolly,
        DollyFlatbed,
        FileMedical,
        FileMedicalAlt,
        FirstAid,
        HospitalAlt,
        HospitalSymbol,
        IdCardAlt,
        NotesMedical,
        Pallet,
        Pills,
        PrescriptionBottle,
        PrescriptionBottleAlt,
        Procedures,
        ShippingFast,
        Smoking,
        Syringe,
        Tablets,
        Thermometer,
        Vial,
        Vials,
        Warehouse,
        Weight,
        XRay,
        BoxOpen,
        CommentDots,
        CommentSlash,
        Couch,
        Donate,
        Dove,
        HandHolding,
        HandHoldingHeart,
        HandHoldingUsd,
        HandHoldingWater,
        Hands,
        HandsHelping,
        ParachuteBox,
        PeopleCarry,
        PiggyBank,
        Ribbon,
        Route,
        Seedling,
        Sign,
        SmileWink,
        Tape,
        TruckLoading,
        TruckMoving,
        VideoSlash,
        WineGlass,
        FontAwesomeLogoFull,
        UserAltSlash,
        UserAstronaut,
        UserCheck,
        UserClock,
        UserCog,
        UserEdit,
        UserFriends,
        UserGraduate,
        UserLock,
        UserMinus,
        UserNinja,
        UserShield,
        UserSlash,
        UserTag,
        UserTie,
        UsersCog,
        BalanceScaleLeft,
        BalanceScaleRight,
        Blender,
        BookOpen,
        BroadcastTower,
        Broom,
        Chalkboard,
        ChalkboardTeacher,
        Church,
        Coins,
        CompactDisc,
        Crow,
        Crown,
        Dice,
        DiceFive,
        DiceFour,
        DiceOne,
        DiceSix,
        DiceThree,
        DiceTwo,
        Divide,
        DoorClosed,
        DoorOpen,
        Equals,
        Feather,
        Frog,
        GasPump,
        Glasses,
        GreaterThan,
        GreaterThanEqual,
        Helicopter,
        Infinity,
        KiwiBird,
        LessThan,
        LessThanEqual,
        Memory,
        MicrophoneAltSlash,
        MoneyBillWave,
        MoneyBillWaveAlt,
        MoneyCheck,
        MoneyCheckAlt,
        NotEqual,
        Palette,
        Parking,
        Percentage,
        ProjectDiagram,
        Receipt,
        Robot,
        Ruler,
        RulerCombined,
        RulerHorizontal,
        RulerVertical,
        School,
        Screwdriver,
        ShoePrints,
        Skull,
        SmokingBan,
        Store,
        StoreAlt,
        Stream,
        Stroopwafel,
        Toolbox,
        Tshirt,
        Walking,
        Wallet,
        Angry,
        Archway,
        Atlas,
        Award,
        Backspace,
        BezierCurve,
        Bong,
        Brush,
        BusAlt,
        Cannabis,
        CheckDouble,
        Cocktail,
        ConciergeBell,
        Cookie,
        CookieBite,
        CropAlt,
        DigitalTachograph,
        Dizzy,
        DraftingCompass,
        Drum,
        DrumSteelpan,
        FeatherAlt,
        FileContract,
        FileDownload,
        FileExport,
        FileImport,
        FileInvoice,
        FileInvoiceDollar,
        FilePrescription,
        FileSignature,
        FileUpload,
        Fill,
        FillDrip,
        Fingerprint,
        Fish,
        Flushed,
        FrownOpen,
        GlassMartiniAlt,
        GlobeAfrica,
        GlobeAmericas,
        GlobeAsia,
        Grimace,
        Grin,
        GrinAlt,
        GrinBeam,
        GrinBeamSweat,
        GrinHearts,
        GrinSquint,
        GrinSquintTears,
        GrinStars,
        GrinTears,
        GrinTongue,
        GrinTongueSquint,
        GrinTongueWink,
        GrinWink,
        GripHorizontal,
        GripVertical,
        HeadphonesAlt,
        Headset,
        Highlighter,
        HotTub,
        Hotel,
        Joint,
        Kiss,
        KissBeam,
        KissWinkHeart,
        Laugh,
        LaughBeam,
        LaughSquint,
        LaughWink,
        LuggageCart,
        MapMarked,
        MapMarkedAlt,
        Marker,
        Medal,
        MehBlank,
        MehRollingEyes,
        Monument,
        MortarPestle,
        PaintRoller,
        Passport,
        PenFancy,
        PenNib,
        PencilRuler,
        PlaneArrival,
        PlaneDeparture,
        Prescription,
        SadCry,
        SadTear,
        ShuttleVan,
        Signature,
        SmileBeam,
        SolarPanel,
        Spa,
        Splotch,
        SprayCan,
        Stamp,
        StarHalfAlt,
        SuitcaseRolling,
        Surprise,
        Swatchbook,
        Swimmer,
        SwimmingPool,
        TintSlash,
        Tired,
        Tooth,
        UmbrellaBeach,
        VectorSquare,
        WeightHanging,
        WineGlassAlt,
        AirFreshener,
        AppleAlt,
        Atom,
        Bone,
        BookReader,
        Brain,
        CarAlt,
        CarBattery,
        CarCrash,
        CarSide,
        ChargingStation,
        Directions,
        DrawPolygon,
        LaptopCode,
        LayerGroup,
        Lungs,
        Microscope,
        OilCan,
        Poop,
        Shapes,
        StarOfLife,
        Teeth,
        TeethOpen,
        TheaterMasks,
        TrafficLight,
        TruckMonster,
        TruckPickup,
        Ad,
        Ankh,
        Bible,
        BusinessTime,
        City,
        CommentDollar,
        CommentsDollar,
        Cross,
        Dharmachakra,
        EnvelopeOpenText,
        FolderMinus,
        FolderPlus,
        FunnelDollar,
        Gopuram,
        Hamsa,
        Bahai,
        Jedi,
        JournalWhills,
        Kaaba,
        Khanda,
        Landmark,
        MailBulk,
        Menorah,
        Mosque,
        Om,
        Pastafarianism,
        Peace,
        PlaceOfWorship,
        Poll,
        PollH,
        Pray,
        PrayingHands,
        Quran,
        SearchDollar,
        SearchLocation,
        Socks,
        SquareRootAlt,
        StarAndCrescent,
        StarOfDavid,
        Synagogue,
        Torah,
        ToriiGate,
        Vihara,
        VolumeMute,
        YinYang,
        BlenderPhone,
        BookDead,
        Campground,
        Cat,
        Chair,
        CloudMoon,
        CloudSun,
        DiceD20,
        DiceD6,
        Dog,
        Dragon,
        DrumstickBite,
        Dungeon,
        FileCsv,
        FistRaised,
        Ghost,
        Hammer,
        Hanukiah,
        HatWizard,
        Hiking,
        Hippo,
        Horse,
        HouseDamage,
        Hryvnia,
        Mask,
        Mountain,
        NetworkWired,
        Otter,
        Ring,
        Running,
        Scroll,
        SkullCrossbones,
        Slash,
        Spider,
        ToiletPaper,
        Tractor,
        UserInjured,
        VrCardboard,
        Wind,
        WineBottle,
        CloudMeatball,
        CloudMoonRain,
        CloudRain,
        CloudShowersHeavy,
        CloudSunRain,
        Democrat,
        FlagUsa,
        Meteor,
        PersonBooth,
        PooStorm,
        Rainbow,
        Republican,
        Smog,
        TemperatureHigh,
        TemperatureLow,
        VoteYea,
        Water,
        Baby,
        BabyCarriage,
        Biohazard,
        Blog,
        CalendarDay,
        CalendarWeek,
        CandyCane,
        Carrot,
        CashRegister,
        CompressArrowsAlt,
        Dumpster,
        DumpsterFire,
        Ethernet,
        Gifts,
        GlassCheers,
        GlassWhiskey,
        GlobeEurope,
        GripLines,
        GripLinesVertical,
        Guitar,
        HeartBroken,
        HollyBerry,
        HorseHead,
        Icicles,
        Igloo,
        Mitten,
        MugHot,
        Radiation,
        RadiationAlt,
        Restroom,
        Satellite,
        SatelliteDish,
        SdCard,
        SimCard,
        Skating,
        Skiing,
        SkiingNordic,
        Sleigh,
        Sms,
        Snowboarding,
        Snowman,
        Snowplow,
        Tenge,
        Toilet,
        Tools,
        Tram,
        FireAlt,
        Bacon,
        BookMedical,
        BreadSlice,
        Cheese,
        ClinicMedical,
        CommentMedical,
        Crutch,
        Disease,
        Egg,
        Hamburger,
        HandMiddleFinger,
        HardHat,
        HospitalUser,
        Hotdog,
        IceCream,
        LaptopMedical,
        Pager,
        PepperHot,
        PizzaSlice,
        TrashRestore,
        TrashRestoreAlt,
        UserNurse,
        WaveSquare,
        Biking,
        BorderAll,
        BorderNone,
        BorderStyle,
        Fan,
        Icons,
        PhoneAlt,
        PhoneSquareAlt,
        PhotoVideo,
        RemoveFormat,
        SortAlphaDownAlt,
        SortAlphaUpAlt,
        SortAmountDownAlt,
        SortAmountUpAlt,
        SortNumericDownAlt,
        SortNumericUpAlt,
        SpellCheck,
        Voicemail,
        HatCowboy,
        HatCowboySide,
        Mouse,
        RecordVinyl,
        Caravan,
        Faucet,
        Trailer,
        BoxTissue,
        HandHoldingMedical,
        HandSparkles,
        HandsWash,
        HandshakeAltSlash,
        HandshakeSlash,
        HeadSideCough,
        HeadSideCoughSlash,
        HeadSideMask,
        HeadSideVirus,
        HouseUser,
        LaptopHouse,
        LungsVirus,
        PeopleArrows,
        PlaneSlash,
        PumpMedical,
        PumpSoap,
        ShieldVirus,
        Soap,
        Stopwatch20,
        StoreAltSlash,
        StoreSlash,
        ToiletPaperSlash,
        Virus,
        VirusSlash,
        Viruses
    }
}
